{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "trading-app.fullname" . }}
  labels:
    {{- include "trading-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "trading-app.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: External
      external:
        metric:
          name: "rate(ticks_total[1m])"
        target:
          type: Value
          value: {{ .Values.hpa.targetValue | quote }}
{{- end }}
