# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63r.proto\x12\x10loom.quantengine\"3\n\rReplaceParams\x12\x11\n\tnew_price\x18\x01 \x01(\x01\x12\x0f\n\x07new_qty\x18\x02 \x01(\x05\"{\n\x14\x43\x61ncelReplaceRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x04\x12/\n\x06params\x18\x02 \x01(\x0b\x32\x1f.loom.quantengine.ReplaceParams\x12\r\n\x05ts_ns\x18\x03 \x01(\x04\x12\x11\n\tnew_price\x18\x04 \x01(\x01\"3\n\x10\x43\x61ncelReplaceAck\x12\x10\n\x08order_id\x18\x01 \x01(\x04\x12\r\n\x05ts_ns\x18\x02 \x01(\x04\"7\n\x13\x43\x61ncelReplaceReject\x12\x10\n\x08order_id\x18\x01 \x01(\x04\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPLACEPARAMS']._serialized_start=30
  _globals['_REPLACEPARAMS']._serialized_end=81
  _globals['_CANCELREPLACEREQUEST']._serialized_start=83
  _globals['_CANCELREPLACEREQUEST']._serialized_end=206
  _globals['_CANCELREPLACEACK']._serialized_start=208
  _globals['_CANCELREPLACEACK']._serialized_end=259
  _globals['_CANCELREPLACEREJECT']._serialized_start=261
  _globals['_CANCELREPLACEREJECT']._serialized_end=316
# @@protoc_insertion_point(module_scope)
