# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x0cshared_proto\"\xb0\x01\n\nMarketTick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x12\n\nts_unix_ns\x18\x02 \x01(\x03\x12\x11\n\tbid_price\x18\x03 \x01(\x01\x12\x11\n\task_price\x18\x04 \x01(\x01\x12\x12\n\nlast_price\x18\x05 \x01(\x01\x12\x10\n\x08\x62id_size\x18\x06 \x01(\x05\x12\x10\n\x08\x61sk_size\x18\x07 \x01(\x05\x12\x11\n\tlast_size\x18\x08 \x01(\x05\x12\r\n\x05venue\x18\t \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETTICK']._serialized_start=36
  _globals['_MARKETTICK']._serialized_end=212
# @@protoc_insertion_point(module_scope)
