# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared_proto/envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shared_proto/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import cr_pb2 as proto_dot_cr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bshared_proto/envelope.proto\x12\x0cshared_proto\x1a\x0eproto/cr.proto\"\xb9\x01\n\x08\x45nvelope\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x10\n\x08msg_type\x18\x03 \x01(\t\x12\x31\n\x0csimple_order\x18\n \x01(\x0b\x32\x19.shared_proto.SimpleOrderH\x00\x12\x34\n\x02\x63r\x18\x0b \x01(\x0b\x32&.loom.quantengine.CancelReplaceRequestH\x00\x42\t\n\x07payload\"t\n\x0bSimpleOrder\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x05\x12\x12\n\norder_type\x18\x04 \x01(\t\x12\x13\n\x0blimit_price\x18\x05 \x01(\x01\x12\x0f\n\x07\x61\x63\x63ount\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared_proto.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=62
  _globals['_ENVELOPE']._serialized_end=247
  _globals['_SIMPLEORDER']._serialized_start=249
  _globals['_SIMPLEORDER']._serialized_end=365
# @@protoc_insertion_point(module_scope)
