name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] || pip install -r requirements.txt

      # Standard unit tests (quick feedback)
      - name: Run unit tests (serial)
        run: pytest -q

      # Run in parallel (catch race/scale issues, fails build on error)
      - name: Run parallel/stress tests
        run: pytest -q -n auto --maxfail=3 --dist=loadfile

      # Optionally, run "chaos monkey" tests if you mark them (use @pytest.mark.chaos in your test_chaos.py)
      - name: Run chaos/chaos-monkey tests (if present)
        run: pytest -q -m chaos || echo "No chaos tests found"

      # Lint important scripts (fail CI on syntax errors)
      - name: Lint important scripts
        run: |
          python -m py_compile scripts/cancel_replace_receiver.py scripts/demo_sender.py scripts/core.py || exit 1

      # Optionally: check formatting (black, isort, flake8, etc.)
      - name: Check code style (optional)
        run: |
          pip install black isort flake8
          black --check .
          isort --check .
          flake8 .
