name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]    # or just requirements.txt

      - name: Run unit tests
        run: pytest -q

      # Smoke-compile important scripts
      - name: Lint important scripts
        run: |
          python -m py_compile scripts/cancel_replace_receiver.py \
                                 scripts/demo_sender.py
